/*
 * Omarchy Dynamic GTK4 Theme Template for Nautilus
 * Automatically generated by Omarchy Quattro theme switcher
 */

/* 1. Dynamic Omarchy Variables */
@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};

@define-color view_bg_color {{ background }};
@define-color view_fg_color {{ foreground }};

@define-color headerbar_bg_color {{ background }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ color8 }};

/* Use GTK's shade() to dynamically lighten/darken panels relative to the background */
@define-color card_bg_color shade({{ background }}, 1.2);
@define-color card_fg_color {{ foreground }};
@define-color popover_bg_color shade({{ background }}, 1.2);
@define-color popover_fg_color {{ foreground }};

@define-color sidebar_bg_color shade({{ background }}, 0.85); 
@define-color sidebar_fg_color {{ foreground }};

@define-color accent_color {{ accent }};
@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ background }};

/* Status Colors */
@define-color destructive_color {{ red }};
@define-color destructive_bg_color {{ red }};
@define-color destructive_fg_color {{ background }};

@define-color success_color {{ green }};
@define-color success_bg_color {{ green }};
@define-color success_fg_color {{ background }};

@define-color warning_color {{ yellow }};
@define-color warning_bg_color {{ yellow }};
@define-color warning_fg_color {{ background }};

@define-color error_color {{ red }};
@define-color error_bg_color {{ red }};
@define-color error_fg_color {{ background }};


/* 2. Nautilus Specific Overrides */

/* Dynamic font hook placeholder, ridimensionamento all'85% e pulizia bordi Libadwaita */
window.nautilus-window {
    font-family: 'Placeholder', monospace;
    font-size: 85%;
    --headerbar-border-color: transparent;
    --headerbar-shade-color: transparent;
    --headerbar-darker-shade-color: transparent;
}

/* Rimuove l'ombra undershoot della top bar */
window.nautilus-window undershoot.top {
    background-image: none;
    background-color: transparent;
    box-shadow: none;
}

/* Ripristina il separatore verticale standard tra sidebar e vista principale */
window.nautilus-window separator {
    background-color: @headerbar_border_color;
    min-width: 1px;
}

/* Main View */
window.nautilus-window,
window.nautilus-window base,
.nautilus-window notebook,
.nautilus-window view {
    background-color: @view_bg_color;
    color: @view_fg_color;
}

/* Top Bar */
window.nautilus-window headerbar,
window.nautilus-window .titlebar {
    background-color: @headerbar_bg_color;
    color: @headerbar_fg_color;
    border: none;
    box-shadow: none;
}

.nautilus-path-bar button {
    background-color: transparent;
    color: @window_fg_color;
    font-weight: normal;
    border-radius: 0;
}
.nautilus-path-bar button:hover {
    background-color: @card_bg_color;
    color: @accent_color;
    border-radius: 0;
}

/* Sidebar */
window.nautilus-window placessidebar {
    background-color: @sidebar_bg_color;
    color: @sidebar_fg_color;
}
window.nautilus-window placessidebar row {
    border-radius: 0;
}
window.nautilus-window placessidebar row:selected {
    background-color: alpha(@accent_bg_color, 0.15);
    color: @accent_color;
    font-weight: normal;
    border-radius: 0;
}
window.nautilus-window placessidebar row:hover:not(:selected) {
    background-color: alpha(@headerbar_border_color, 0.2);
    border-radius: 0;
}

/* Main View items / folders (Grid, List, Column views, and Icon View / Grid cells) */
window.nautilus-window flowboxchild,
window.nautilus-window .nautilus-view-kanban .card,
window.nautilus-window gridview child,
window.nautilus-window columnview row,
window.nautilus-window listview row,
window.nautilus-window .view item {
    border-radius: 0;
}

window.nautilus-window flowboxchild:hover,
window.nautilus-window gridview child:hover,
window.nautilus-window columnview row:hover,
window.nautilus-window listview row:hover,
window.nautilus-window .view item:hover {
    background-color: alpha(@headerbar_border_color, 0.2);
    border-radius: 0;
}

window.nautilus-window flowboxchild:selected,
window.nautilus-window gridview child:selected,
window.nautilus-window treeview:selected,
window.nautilus-window columnview row:selected,
window.nautilus-window listview row:selected,
window.nautilus-window .view item:selected {
    background-color: alpha(@accent_bg_color, 0.15);
    color: @window_fg_color;
    border-radius: 0;
    outline: none;
    box-shadow: none;
}

rubberband, .rubberband {
    background-color: alpha(@accent_bg_color, 0.20);
    border: 1px solid @accent_bg_color;
    border-radius: 0;
}

window.nautilus-window button:not(.flat):not(.suggested-action):not(.destructive-action) {
    background-color: @card_bg_color;
    color: @window_fg_color;
    border: 1px solid @headerbar_border_color;
    border-radius: 0;
}
window.nautilus-window button:hover:not(.flat) {
    background-color: shade(@card_bg_color, 1.5); 
    color: @window_fg_color;
    border-radius: 0;
}
window.nautilus-window button:checked,
window.nautilus-window button:active {
    background-color: @accent_bg_color;
    color: @accent_fg_color;
    border-radius: 0;
}

window.nautilus-window entry {
    background-color: @sidebar_bg_color;
    color: @window_fg_color;
    border: 1px solid @headerbar_border_color;
    border-radius: 0;
}
window.nautilus-window entry:focus {
    border-color: @accent_color;
    box-shadow: 0 0 0 2px alpha(@accent_color, 0.3);
    border-radius: 0;
}

scrollbar slider {
    background-color: @headerbar_border_color;
    border-radius: 0;
}
scrollbar slider:hover,
scrollbar slider:active {
    background-color: @accent_color;
    border-radius: 0;
}

box {
border-radius:0px;}
