/*
 * Omarchy Dynamic GTK4 Theme Template for Nautilus
 * Automatically generated by Omarchy theme switcher
 */

/* 1. Dynamic Omarchy & Libadwaita Variables */
@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};

@define-color view_bg_color {{ background }};
@define-color view_fg_color {{ foreground }};

@define-color headerbar_bg_color {{ background }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ color8 }};

/* Surface & Panel Colors using Omarchy mix functions */
@define-color card_bg_color {{ mix background foreground 6% }};
@define-color card_fg_color {{ foreground }};
@define-color popover_bg_color {{ mix background foreground 8% }};
@define-color popover_fg_color {{ foreground }};

@define-color sidebar_bg_color {{ mix background foreground 3% }};
@define-color sidebar_fg_color {{ foreground }};
@define-color sidebar_backdrop_color {{ background }};
@define-color secondary_sidebar_bg_color {{ mix background foreground 3% }};

@define-color dialog_bg_color {{ mix background foreground 6% }};
@define-color dialog_fg_color {{ foreground }};

/* Selection Colors */
@define-color theme_selected_bg_color {{ selection }};
@define-color theme_selected_fg_color {{ selection_foreground }};

/* Accent Colors */
@define-color accent_color {{ accent }};
@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ bright_foreground }};

/* Status Colors */
@define-color destructive_color {{ red }};
@define-color destructive_bg_color {{ red }};
@define-color destructive_fg_color {{ background }};

@define-color success_color {{ green }};
@define-color success_bg_color {{ green }};
@define-color success_fg_color {{ background }};

@define-color warning_color {{ yellow }};
@define-color warning_bg_color {{ yellow }};
@define-color warning_fg_color {{ background }};

@define-color error_color {{ red }};
@define-color error_bg_color {{ red }};
@define-color error_fg_color {{ background }};


/* 2. Nautilus Specific Overrides */

/* JetBrains Mono typography, 85% base scaling, and Libadwaita border cleanup */
window.nautilus-window {
    font-family: "JetBrainsMono", "JetBrains Mono", monospace;
    font-size: 85%;
    --headerbar-border-color: transparent;
    --headerbar-shade-color: transparent;
    --headerbar-darker-shade-color: transparent;
}

/* Remove top bar undershoot shadow */
window.nautilus-window undershoot.top {
    background-image: none;
    background-color: transparent;
    box-shadow: none;
}

/* Restore standard vertical separator between sidebar and main view */
window.nautilus-window separator.vertical {
    background-color: @headerbar_border_color;
    min-width: 1px;
}

/* Main View */
window.nautilus-window,
window.nautilus-window base,
.nautilus-window notebook,
.nautilus-window view {
    background-color: @view_bg_color;
    color: @view_fg_color;
}

/* Top Bar */
window.nautilus-window headerbar,
window.nautilus-window .titlebar {
    background-color: @headerbar_bg_color;
    color: @headerbar_fg_color;
    border: none;
    box-shadow: none;
}

.nautilus-path-bar button {
    background-color: transparent;
    color: @window_fg_color;
    border-radius: 0;
}
.nautilus-path-bar button:hover {
    background-color: @card_bg_color;
    color: @accent_color;
    border-radius: 0;
}

/* Sidebar */
.nautilus-window placessidebar {
    background-color: @sidebar_bg_color;
    color: @sidebar_fg_color;
}
.nautilus-window placessidebar row {
    border-radius: 0;
}
.nautilus-window placessidebar row:selected {
    background-color: alpha(@accent_bg_color, 0.25);
    color: @accent_color;
    border-radius: 0;
}
.nautilus-window placessidebar row:hover:not(:selected) {
    background-color: alpha(@headerbar_border_color, 0.2);
    border-radius: 0;
}

/* Main View items / folders (Grid, List, Column views, and Icon View / Grid cells) */
.nautilus-window flowboxchild,
.nautilus-window .nautilus-view-kanban .card,
.nautilus-window gridview child,
.nautilus-window columnview row,
.nautilus-window listview row,
.nautilus-window .view item {
    border-radius: 0;
}

.nautilus-window flowboxchild:hover,
.nautilus-window gridview child:hover,
.nautilus-window columnview row:hover,
.nautilus-window listview row:hover,
.nautilus-window .view item:hover {
    background-color: alpha(@headerbar_border_color, 0.2);
    border-radius: 0;
}

.nautilus-window flowboxchild:selected,
.nautilus-window gridview child:selected,
.nautilus-window treeview:selected,
.nautilus-window columnview row:selected,
.nautilus-window listview row:selected,
.nautilus-window .view item:selected {
    background-color: alpha(@accent_bg_color, 0.25);
    color: @theme_selected_fg_color;
    border-radius: 0;
}

rubberband, .rubberband {
    background-color: alpha(@accent_bg_color, 0.20);
    border: 1px solid @accent_bg_color;
    border-radius: 0;
}

.nautilus-window button:not(.flat):not(.suggested-action):not(.destructive-action) {
    background-color: @card_bg_color;
    color: @window_fg_color;
    border: 1px solid @headerbar_border_color;
    border-radius: 0;
}
.nautilus-window button:hover:not(.flat) {
    background-color: shade(@card_bg_color, 1.3); 
    color: @window_fg_color;
    border-radius: 0;
}
.nautilus-window button:checked,
.nautilus-window button:active {
    background-color: @accent_bg_color;
    color: @accent_fg_color;
    border-radius: 0;
}

.nautilus-window entry {
    background-color: @sidebar_bg_color;
    color: @window_fg_color;
    border: 1px solid @headerbar_border_color;
    border-radius: 0;
}
.nautilus-window entry:focus {
    border-color: @accent_color;
    box-shadow: 0 0 0 2px alpha(@accent_color, 0.3);
    border-radius: 0;
}

scrollbar slider {
    background-color: @headerbar_border_color;
    border-radius: 0;
}
scrollbar slider:hover,
scrollbar slider:active {
    background-color: @accent_color;
    border-radius: 0;
}
